version: "3"
services:
  server:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: "${DATABASE_URL}"
      NODE_ENV: development
      PORT: 3001
    ports:
      - "3001:3001"
    command: sh ./start.sh
    volumes:
      - .:/app/

  postgres:
    image: postgres:12.4
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 5s
      retries: 5

